### PR TITLE
Bump phoenix_html

### PR DESCRIPTION
**Pull request by marcandre**
Tests pass locally.
This is needed to upgrade to `phoenix` 1.16

### CODE REVIEW

**Review by mjcloutier — APPROVED** [review]

**Review by doomspork — APPROVED** [review]

**Comment by marcandre** [comment]
Thanks for merging. Can we get a release please?

**Comment by marcandre** [comment]
Ping: can we get a release please?

**Comment by fuelen** [comment]
ping

**Comment by asheehan** [comment]
bump

**Pull request merged**
