### PR TITLE
Bump phoenix html

### PR DESCRIPTION
**Pull request by zazaian**
This PR bumps `phoenix_html` from `~> 2.6` to `~> 2.10`. Current version is `2.10.3`.

All tests passing.

### CODE REVIEW

**Comment by jonmast** [comment]
@zazaian This PR appears to be identical to #51, am I missing something?

**Comment by zazaian** [comment]
Hi there @jonmast - sorry, didn't realize I'd submitted two here. I think I intended to issue an incremental release on my own fork and accidentally issued a PR. You should be able to merge #51 and close #52 and everything should be current.

**Comment by zazaian** [comment]
P.S. nice work on `phoenix_slime`, it seems to be the most complete and well-supported minimalist templating library in the elixir ecosystem right now, including the available options for haml and pug. In a young ecosystem like this having a reliable library like this is invaluable for relying upon to build production-ready tools, and you guys seem to be doing a great job. Thanks again.

**Comment by doomspork** [comment]
Thanks @zazaian!  I'll close this in favor of #51

**Pull request closed without merging**
